version: '3'
services:
    app:
        build: .
        working_dir: /app/src
        command: flask run --host=0.0.0.0
        environment:
            - FLASK_APP=main.py
            - FLASK_ENV=development
        ports:
            - '5000:5000'
        volumes:
            - ./src/:/app/src